CREATE DATABASE DES_SUPER

CREATE TABLE [dbo].[C_UNIDADES](
	[UNI_ID] [INT] IDENTITY (1,1) NOT NULL,
	[UNI_NOMBRE] [VARCHAR](100) NOT NULL,
	[UNI_SIGLA] [VARCHAR](10),
	[UNI_ESTADO] [INT],
	[UNI_FECHAALTA] [DATETIME],
	[UNI_FECHAMODIFICADA] [DATETIME],
	PRIMARY KEY [UNI_ID]
)

CREATE TABLE [dbo].[C_FAMILIA](
	[FAM_ID] [INT] IDENTITY (1,1) NOT NULL,
	[FAM_NOMBRE] [VARCHAR](100) NOT NULL,
	[FAM_DESCRIPCION] [VARCHAR](250),
	[FAM_ESTADO] [INT] DEFAULT 1,
	[FAM_FECHAALTA] [DATETIME] ,
	[FAM_FECHAMODIFICADA] [DATETIME],
	PRIMARY KEY [FAM_ID]
)

CREATE TABLE [dbo].[C_RUBRO](
	[RUB_ID] [INT] IDENTITY (1,1) NOT NULL,
	[RUB_NOMBRE] [VARCHAR](100) NOT NULL,
	[RUB_DESCRIPCION] [VARCHAR](250),
	[FAM_ID] [INT],
	[RUB_ESTADO] [INT] DEFAULT 1,
	[RUB_FECHAALTA] [DATETIME],
	[RUB_FECHAMODIFICADA] [DATETIME],
	PRIMARY KEY [RUB_ID],
	CONSTRAINT [PK_RUBRO_FAMILIA] [FAM_ID] REFERENCES [C_FAMILIA] ([FAM_ID])
)

CREATE TABLE [dbo].[C_PRODUCTO](
	[PRO_ID] [INT] IDENTITY (1,1) NOT NULL,
	[PRO_CODIGO] [VARCHAR](20),
	[PRO_NOMBRE] [VARCHAR](250) NOT NULL,
	[PRO_DESCRIPCION] [VARCHAR](500),
	[PRO_MARCA] [VARCHAR](100),
	[PRO_PRECIOCOSTO] [NUMERIC] (18,2),
	[PRO_PRECIOCOMPRA] [NUMERIC](18,2),
	[PRO_IVA] [NUMERIC] (18,2),
	[PRO_IMPUESTOINTERNO] [NUMERIC](18,2),
	[PRO_IDPADRE] [INT],
	[PRO_MINIMO] [INT],
	[PRO_MAXIMO] [INT],
	[PRO_ALERTA] [INT],	
	[UNC_ID] [INT], -- UNIDAD DE COMPRA
	[UNV_ID] [INT], -- UNIDAD DE VENTA
	[RUB_ID] [INT], -- RUBRO
	[FAM_ID] [INT], -- FAMILIA
	PRIMARY KEY [PRO_ID],
	CONSTRAINT [PK_PRODUCTO_UNIDAD_COMPRA] [UNC_ID] REFERENCES [C_UNIDADES] [UNI_ID],
	CONSTRAINT [PK_PRODUCTO_UNIDAD_VENTA] [UNV_ID] REFERENCES [C_UNIDADES] [UNI_ID],
	CONSTRAINT [PK_PRODUCTO_RUBRO] [RUB_ID] REFERENCES [C_RUBRO] [RUB_ID],
	CONSTRAINT [PK_PRODUCTO_FAMILIA] [FAM_ID] REFERENCES [C_FAMILIA] FAM_ID]
)