
CREATE PROCEDURE [dbo].[STR_NUEVO_RUBRO](
	@RUB_ID AS INT OUTPUT,
	@RUB_NOMBRE AS VARCHAR(100),
	@RUB_DESCRIPCION AS VARCHAR(250),
	@RUB_ESTADO AS INT,
)

AS

BEGIN

	BEGIN TRANSACTION 
		BEGIN TRY
			INSERT INTO RUBRO (RUB_NOMBRE,RUB_DESCRIPCION,RUB_ESTADO,RUB_FECHAALTA)
			VALUES (@RUB_NOMBRE,@RUB_DESCRIPCION,@RUB_ESTADO,GETDATE())
			SET @RUB_ID = @@IDENTITY		
			RETURN @RUB_ID
		END TRY
	COMMIT TRANSATION 

	BEGIN CATCH
		SELECT ERROR_MESSAGE(),ERROR_NUMBER()
		ROLLBACK TRANSACTION 	
		SET @RUB_ID = -1
		RETURN @RUB_ID
	END CATCH
END




CREATE PROCEDURE [dbo].[STR_MODIFICA_RUBRO](
	@RUB_ID AS INT OUTPUT,
	@RUB_NOMBRE AS VARCHAR(100),
	@RUB_DESCRIPCION AS VARCHAR(250),
	@RUB_ESTADO AS INT,
)

AS

BEGIN

	BEGIN TRANSACTION 
		BEGIN TRY
			IF(@RUB_ESTADO = 2)
				BEGIN
					UPDATE RUBRO
						SET RUB_ESTADO = @RUB_ESTADO
					WHERE RUB_ID = @RUB_ID
				END
			ELSE
				BEGIN
					UPDATE RUBRO
						SET RUB_NOMBRE = @RUB_NOMBRE,
						    RUB_DESCRIPCION = @RUB_DESCRIPCION,
						    RUB_FECHAMODIFICADO = GETDATE()
					WHERE RUB_ID = @RUB_ID
				END
		END TRY
	COMMIT TRANSATION 

	BEGIN CATCH
		SELECT ERROR_MESSAGE(),ERROR_NUMBER()
		ROLLBACK TRANSACTION 	
		SET @RUB_ID = -1
		RETURN @RUB_ID
	END CATCH
END

CREATE PROCEDURE [dbo].[STR_NUEVO _PRODUCTO]